### ISSUE TITLE
Wrong palettes in Fortree City's Gym

### ISSUE THREAD

**Issue by LOuroboros** [ExpoSeed/pokeemerald#5]
Left: Vanilla | Right: dynamic-ow-pals
![vanilla](https://user-images.githubusercontent.com/4485172/147968077-358e5e5c-f2dc-4577-bdef-de11d263671b.png)![mGBA_3133](https://user-images.githubusercontent.com/4485172/147968072-d3d2a696-bef8-44bd-b35b-253a379a3bfd.png)

**Comment by ExpoSeed** [comment]
2a4f6600f074f5fcd9aca7c93e23c99f15543061

thank you to cbt for the fix
